import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'Plant Tracker',
        short_name: 'Plants',
        description: 'Track your plant watering and care',
        // Matches --cactus (app bars) and --paper (app background) in global.css.
        theme_color: '#2F6E47',
        background_color: '#FBF3E4',
        display: 'standalone',
        // PNG rather than SVG — iOS and some Android launchers won't take SVG
        // manifest icons. Generated by scripts/render-icons.mjs.
        icons: [
          {
            src: '/icon-192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/icon-512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: '/icon-maskable-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: '/icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
});
